name: note_mory
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts: 
  #   - family: Fontserrat
  #     fonts: 
  #       - asset: assets/fonts/Montserrat-ExtraBold.ttf
  #       - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
  #       - asset: assets/fonts/Montserrat-VariableFont_wght.ttf

flutter_native_splash:
  color: "#440C0C" 
  image: assets/images/note_memo_icon.png 
  android: true 
  ios: true 
  web: false